-- pg_net (20260915045648_scheduled_weather_sync.sql) was installed with
-- no explicit schema, landing its extension registration in `public` --
-- the one extension in this project that doesn't follow the convention
-- already established for postgis and pg_trgm (both `with schema
-- extensions`), and exactly what the security advisor's "Extension in
-- Public" check flags. Caught during the pre-release advisor check
-- required by CONTRIBUTING.md's release process.
--
-- This only moves the extension's own catalog registration -- pg_net's
-- functions (net.http_post, used by the hourly weather-sync cron job)
-- already live in their own fixed `net` schema regardless of which
-- schema the extension itself is grouped under, so the cron job's call
-- is unaffected.
alter extension pg_net set schema extensions;
