-- Scheduled weather sync (docs/decisions/0020): revisits 0019's "no
-- service_role, no pg_cron/pg_net" decision now that real use showed the
-- "only refreshes while someone has the app open" trade-off wasn't
-- acceptable. pg_cron invokes a new Edge Function (sync-scheduled-weather)
-- hourly; this migration is everything that lives in Postgres to support
-- that: the two extensions, a random caller secret nobody ever has to
-- type or transmit, the one SECURITY DEFINER function that checks that
-- secret and hands back every enabled source's decrypted credential in a
-- single call (vault.decrypted_secrets isn't reachable via PostgREST --
-- only public/graphql_public are exposed per supabase/config.toml -- the
-- same reason private.get_decrypted_source_secret exists for the
-- user-driven path), and the cron schedule itself.
create extension if not exists pg_cron;
create extension if not exists pg_net;

-- A value generated by Postgres itself at apply-time -- never seen, typed,
-- or transmitted by a human, or passed through any tool call. Both sides
-- of the handshake (the cron job below, and the function that checks it)
-- read this same row by name; neither ever hardcodes the value itself.
-- Guarded so re-running this migration (e.g. a local reset) doesn't error
-- on a duplicate name -- vault.create_secret has no native "if not exists".
do $$
begin
  if not exists (select 1 from vault.decrypted_secrets where name = 'weather_sync_trigger_secret') then
    perform vault.create_secret(
      encode(gen_random_bytes(32), 'hex'),
      'weather_sync_trigger_secret',
      'Shared secret proving a request to sync-scheduled-weather really came from this project''s own pg_cron job, not an arbitrary caller. Read by both sides of the handshake; never stored anywhere else. See docs/decisions/0020.'
    );
  end if;
end
$$;

-- The one function in this project that hands back decrypted credentials
-- for every producer's source at once, rather than one caller-owned
-- source at a time -- deliberately narrow: it takes the trigger secret as
-- a parameter and raises before touching anything else if it doesn't
-- match, and execute is revoked from everyone except service_role below,
-- so only sync-scheduled-weather's own admin client can ever call it.
create or replace function public.get_enabled_weather_sources_for_sync(p_trigger_secret text)
returns table (
  id uuid,
  producer_id uuid,
  external_id text,
  backfill_status text,
  backfill_cursor timestamptz,
  backfill_start timestamptz,
  last_synced_at timestamptz,
  api_key text
)
language plpgsql
security definer
set search_path = public, vault
as $$
declare
  expected_secret text;
begin
  select decrypted_secret into expected_secret
  from vault.decrypted_secrets
  where name = 'weather_sync_trigger_secret';

  if expected_secret is null or p_trigger_secret is null or p_trigger_secret <> expected_secret then
    raise exception 'not authorized: bad or missing trigger secret';
  end if;

  return query
    select ds.id, ds.producer_id, ds.external_id, ds.backfill_status,
           ds.backfill_cursor, ds.backfill_start, ds.last_synced_at,
           vs.decrypted_secret as api_key
    from public.data_sources ds
    join vault.decrypted_secrets vs on vs.id = ds.vault_secret_id
    where ds.enabled = true;
end;
$$;

comment on function public.get_enabled_weather_sources_for_sync is 'Checks p_trigger_secret against the Vault-stored weather_sync_trigger_secret and, only if it matches, returns every enabled data_source with its decrypted credential. The one place in this project that reads more than one producer''s secret at a time -- execute is restricted to service_role only, see docs/decisions/0020.';

-- CREATE FUNCTION grants EXECUTE to PUBLIC by default (the same default
-- this project got bitten by once already, see
-- 20260915035815_revoke_public_execute_on_vault_helpers.sql) -- revoke it
-- immediately and grant back only to service_role, which is the only
-- role sync-scheduled-weather's own admin client ever authenticates as.
revoke execute on function public.get_enabled_weather_sources_for_sync(text) from public;
grant execute on function public.get_enabled_weather_sources_for_sync(text) to service_role;

-- Every enabled source gets a bounded catch-up chunk on the hour --
-- Supabase's own documented pg_cron + pg_net pattern for invoking an Edge
-- Function on a schedule. The URL is this project's own real, public,
-- non-secret API URL (same as every other reference to it in this
-- codebase); the one sensitive value is read from Vault at call time,
-- never inlined as a literal.
select cron.schedule(
  'sync-weather-sources-hourly',
  '0 * * * *',
  $$
  select net.http_post(
    url := 'https://fostmbhpnhjzhulphxzp.supabase.co/functions/v1/sync-scheduled-weather',
    headers := jsonb_build_object(
      'Content-Type', 'application/json',
      'X-Cron-Secret', (select decrypted_secret from vault.decrypted_secrets where name = 'weather_sync_trigger_secret')
    ),
    body := '{}'::jsonb
  ) as request_id;
  $$
);
